### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dgevo** [sbaresearch/mbn-mcfg-tools#1]
Hello!
I can't install. Apparently there is a version mismatch:

(tt3) a@ubnt:~/mbn-mcfg-tools/mbn_mcfg_tools/tt3/bin$ ./mbn-tool
Traceback (most recent call last):
  File "./mbn-tool", line 5, in <module>
    from mbn_mcfg_tools.cli import main
  File "/home/a/mbn-mcfg-tools/mbn_mcfg_tools/tt3/lib/python3.8/site-packages/mbn_mcfg_tools/cli.py", line 7, in <module>
    from mbn_mcfg_tools.mbn import Mbn
  File "/home/a/mbn-mcfg-tools/mbn_mcfg_tools/tt3/lib/python3.8/site-packages/mbn_mcfg_tools/mbn.py", line 13, in <module>
    from mbn_mcfg_tools.mcfg import MCFG, MCFG_Item
  File "/home/a/mbn-mcfg-tools/mbn_mcfg_tools/tt3/lib/python3.8/site-packages/mbn_mcfg_tools/mcfg.py", line 380, in <module>
    class MCFG:
  File "/home/a/mbn-mcfg-tools/mbn_mcfg_tools/tt3/lib/python3.8/site-packages/mbn_mcfg_tools/mcfg.py", line 454, in MCFG
    def filenames(self) -> Generator[bytes, None, None]:
TypeError: 'ABCMeta' object is not subscriptable

Any ideas?

**Comment by dgevo** [comment]
Installed Ubuntu 22.04, it worked

**Comment by phfrenzel** [comment]
Hi! The reason for the error was most likely an incompatible Python version (<3.10). I realized the `pyproject.toml` file did not specify a required Python version, which I've added now and should lead to a better error message in the future. Thank you for creating the issue!
